# Theming - Catppuccin Mocha
font: FiraCode Nerd Font Mono 12
background: "#1e1e2ee6"
color: "#cdd6f4"
border: "#89b4fa"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15
rows_per_column: 5
column_padding: 25

# Anchor and margin
anchor: center

# Permits key bindings that conflict with compositor key bindings.
inhibit_compositor_keyboard_shortcuts: false
 
# Try to guess the correct keyboard layout to use.
auto_kbd_layout: true

menu:    
  - key: b
    desc: Decrease
    keep_open: true
    cmd: brightness-decrease
  - key: B
    desc: Increase
    cmd: brightness-increase
    keep_open: true
  - key: c
    desc: Decrease (Warmer)
    cmd: temperature-decrease
    keep_open: true
  - key: C
    desc: Increase (Cooler)
    cmd: temperature-increase
    keep_open: true
  - key: Alt+c
    desc: Reset
    cmd: temperature-reset
    keep_open: true
