# Theming - Catppuccin Mocha
font: FiraCode Nerd Font Mono 12
background: "#1e1e2ee6"
color: "#cdd6f4"
border: "#89b4fa"
separator: " âžœ "
border_width: 2
corner_r: 10
padding: 15
rows_per_column: 5
column_padding: 25

# Anchor and margin
anchor: center

# Permits key bindings that conflict with compositor key bindings.
inhibit_compositor_keyboard_shortcuts: false
 
# Try to guess the correct keyboard layout to use.
auto_kbd_layout: true

menu:    
  - key: l
    desc: Luminance
    submenu:
      - key: "0"
        desc: 100%
        keep_open: true
        cmd: set-brightness 0
      - key: "1"
        desc: 19%
        keep_open: true
        cmd: set-brightness 1
      - key: "2"
        desc: 28%
        keep_open: true
        cmd: set-brightness 2
      - key: "3"
        desc: 37%
        keep_open: true
        cmd: set-brightness 3
      - key: "4"
        desc: 46%
        keep_open: true
        cmd: set-brightness 4
      - key: "5"
        desc: 55%
        keep_open: true
        cmd: set-brightness 5
      - key: "6"
        desc: 63%
        keep_open: true
        cmd: set-brightness 6
      - key: "7"
        desc: 72%
        keep_open: true
        cmd: set-brightness 7
      - key: "8"
        desc: 81%
        keep_open: true
        cmd: set-brightness 8
      - key: "9"
        desc: 90%
        keep_open: true
        cmd: set-brightness 9
        
  - key: h
    desc: Hue
    submenu:
      - key: "0"
        desc: Reset
        keep_open: true
        cmd: set-temperature 0
      - key: "1"
        desc: 1500K
        keep_open: true
        cmd: set-temperature 1
      - key: "2"
        desc: 2050K
        keep_open: true
        cmd: set-temperature 2
      - key: "3"
        desc: 2600K
        keep_open: true
        cmd: set-temperature 3
      - key: "4"
        desc: 3150K
        keep_open: true
        cmd: set-temperature 4
      - key: "5"
        desc: 3700K
        keep_open: true
        cmd: set-temperature 5
      - key: "6"
        desc: 4250K
        keep_open: true
        cmd: set-temperature 6
      - key: "7"
        desc: 4800K
        keep_open: true
        cmd: set-temperature 7
      - key: "8"
        desc: 5350K
        keep_open: true
        cmd: set-temperature 8
      - key: "9"
        desc: 5900K
        keep_open: true
        cmd: set-temperature 9

  - key: b
    desc: Both
    submenu:
      - key: "0"
        desc: 100% / Reset
        keep_open: true
        cmd: set-both 0
      - key: "1"
        desc: 19% / 1500K
        keep_open: true
        cmd: set-both 1
      - key: "2"
        desc: 28% / 2050K
        keep_open: true
        cmd: set-both 2
      - key: "3"
        desc: 37% / 2600K
        keep_open: true
        cmd: set-both 3
      - key: "4"
        desc: 46% / 3150K
        keep_open: true
        cmd: set-both 4
      - key: "5"
        desc: 55% / 3700K
        keep_open: true
        cmd: set-both 5
      - key: "6"
        desc: 63% / 4250K
        keep_open: true
        cmd: set-both 6
      - key: "7"
        desc: 72% / 4800K
        keep_open: true
        cmd: set-both 7
      - key: "8"
        desc: 81% / 5350K
        keep_open: true
        cmd: set-both 8
      - key: "9"
        desc: 90% / 5900K
        keep_open: true
        cmd: set-both 9
